from typing import Protocol, runtime_checkable

from .models import (
    CurrentProjectContext,
    Decision,
    DecisionBrief,
    DecisionFilter,
    DriftResult,
    EvidenceExcerpt,
    IngestResult,
    MemoryOverview,
    MemoryTrace,
    MentalModelView,
    ObservationView,
    OutcomeChain,
    ReviewQueueItem,
    SourceManifestEntry,
    TimelineEvent,
)


@runtime_checkable
class FacadeProtocol(Protocol):
    """Core interface for the DecisionPrint backend."""

    def get_memory_overview(self, user_role: str) -> MemoryOverview: ...
    def list_projects(self, user_role: str) -> list[CurrentProjectContext]: ...
    def get_project_context(self, project_id: str, user_role: str) -> CurrentProjectContext: ...
    def update_project_context(self, context: CurrentProjectContext, user_role: str) -> CurrentProjectContext: ...
    def ingest_source(self, entry: SourceManifestEntry, content: str, user_role: str) -> IngestResult: ...
    def search_decisions(self, filter: DecisionFilter, user_role: str) -> list[Decision]: ...
    def get_decision(self, decision_id: str, user_role: str) -> Decision: ...
    def get_decision_timeline(self, decision_id: str, user_role: str) -> list[TimelineEvent]: ...
    def ask_question(self, question: str, project_id: str, user_role: str) -> DecisionBrief: ...
    def list_drift_cards(self, project_id: str, user_role: str) -> list[DriftResult]: ...
    def get_evidence(self, source_id: str, user_role: str) -> EvidenceExcerpt: ...
    def get_outcome_chain(self, decision_id: str, user_role: str) -> OutcomeChain: ...
    def list_observations(self, user_role: str, topic: str | None = None) -> list[ObservationView]: ...
    def list_mental_models(self, user_role: str) -> list[MentalModelView]: ...
    def get_memory_trace(self, query_id: str, user_role: str) -> MemoryTrace: ...
    def list_review_queue(self, user_role: str) -> list[ReviewQueueItem]: ...
